
# Site settings
title: Data Direction Consulting
email: hello@datadirection.io
description: "Data Direction Consulting, LLC"
intro-text: Test

# Team names, titles and social links
people:
- name: Mark Espina
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: 
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 
  pic: 
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 
  pic:
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 
# Postal address (add as many lines as necessary)
address:
  - line: 
  - line:

# Build settings
markdown: kramdown
permalink: pretty
repository: y7kim.github.io
remote_theme: agency-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
